version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    networks:
      - my_bridge_network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: example
      DB_PASSWORD: example
      DB_NAME: example
    depends_on:
      - db
    networks:
      - my_bridge_network

volumes:
  postgres_data:
    driver: local

networks:
  my_bridge_network:
    driver: bridge